[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["pip install -r python_backend/requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "python3 -m uvicorn python_backend.main:app --host 0.0.0.0 --port $PORT"

